spring:
  datasource:
#      url: jdbc:mysql://123.206.62.148:3306/SMDB?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
      url: jdbc:mysql://127.0.0.1:3306/SMDB?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
      username: root
#      password: 123456
      password: goholee
      driver-class-name: com.mysql.jdbc.Driver
mybatis:
   mapperLocations: classpath:/mapper/*/*.xml
#   configuration: log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
